fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: cargo-check
- repo: local
  hooks:
    - id: fmt
      name: nightly fmt
      entry: cargo +nightly fmt
      language: system
      types: [rust]
      pass_filenames: false
    - id: clippy
      name: clippy
      entry: cargo +nightly clippy --fix --all-features -Z unstable-options --allow-dirty --allow-staged --
      language: system
      types: [rust]
      pass_filenames: false
